-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-30 15:08:37 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE daily_costs (
    id_daily_costs            NUMBER NOT NULL,
    id_job                    NUMBER NOT NULL,
    material_cost             NUMBER,
    fuel_cost                 NUMBER,
    unpredicted_costs         NUMBER,
    unpredicted_costs_details VARCHAR2(1000),
    day                       DATE
);

ALTER TABLE daily_costs ADD CONSTRAINT daily_costs_pk PRIMARY KEY ( id_daily_costs );

CREATE TABLE employees (
    id_employee     NUMBER NOT NULL,
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(60),
    driving_license VARCHAR2(1),
    hire_date       DATE,
    hour_wage       NUMBER
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( id_employee );

CREATE TABLE jobs (
    id_job                   NUMBER NOT NULL,
    principal_id             NUMBER NOT NULL,
    predicted_amount         NUMBER NOT NULL,
    predicted_beginning      DATE NOT NULL,
    predicted_ending         DATE NOT NULL,
    begin                    DATE,
    end                      DATE,
    costs_of_additional_jobs NUMBER,
    price_of_additonal_costs NUMBER,
    is_done                  NUMBER
);

ALTER TABLE jobs ADD CONSTRAINT jobs_pk PRIMARY KEY ( id_job );

CREATE TABLE principals (
    id_principals NUMBER NOT NULL,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(60) NOT NULL,
    city          VARCHAR2(100),
    street        VARCHAR2(100),
    home_number   NUMBER,
    phone_number  NUMBER NOT NULL
);

ALTER TABLE principals ADD CONSTRAINT principals_pk PRIMARY KEY ( id_principals );

CREATE TABLE worked_hours (
    id_worked_hours NUMBER NOT NULL,
    worked_day      DATE NOT NULL,
    worked_hours    NUMBER,
    job_id          NUMBER NOT NULL,
    id_employee     NUMBER NOT NULL
);

ALTER TABLE worked_hours ADD CONSTRAINT worked_hours_pk PRIMARY KEY ( id_worked_hours );

ALTER TABLE jobs
    ADD CONSTRAINT jobs_daily_costs_fk FOREIGN KEY ( id_job )
        REFERENCES daily_costs ( id_daily_costs );

ALTER TABLE jobs
    ADD CONSTRAINT jobs_principals_fk FOREIGN KEY ( principal_id )
        REFERENCES principals ( id_principals );

ALTER TABLE worked_hours
    ADD CONSTRAINT worked_hours_employees_fk FOREIGN KEY ( id_employee )
        REFERENCES employees ( id_employee );

ALTER TABLE worked_hours
    ADD CONSTRAINT worked_hours_jobs_fk FOREIGN KEY ( job_id )
        REFERENCES jobs ( id_job );

CREATE SEQUENCE employees_id_employee_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER employees_id_employee_trg BEFORE
    INSERT ON employees
    FOR EACH ROW
    WHEN ( new.id_employee IS NULL )
BEGIN
    :new.id_employee := employees_id_employee_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
